export const ALL_ORDER_STATUS_REQUEST = "ALL_ORDER_STATUS_REQUEST";
export const ALL_ORDER_STATUS_SUCCESS = "ALL_ORDER_STATUS_SUCCESS";
export const ALL_ORDER_STATUS_FAIL = "ALL_ORDER_STATUS_FAIL";

export const NEW_ORDER_STATUS_REQUEST = "NEW_ORDER_STATUS_REQUEST";
export const NEW_ORDER_STATUS_SUCCESS = "NEW_ORDER_STATUS_SUCCESS";
export const NEW_ORDER_STATUS_RESET = "NEW_ORDER_STATUS_RESET";
export const NEW_ORDER_STATUS_FAIL = "NEW_ORDER_STATUS_FAIL";

export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_RESET = "UPDATE_ORDER_STATUS_RESET";
export const UPDATE_ORDER_STATUS_FAIL = "UPDATE_ORDER_STATUS_FAIL";

export const DELETE_ORDER_STATUS_REQUEST = "DELETE_ORDER_STATUS_REQUEST";
export const DELETE_ORDER_STATUS_SUCCESS = "DELETE_ORDER_STATUS_SUCCESS";
export const DELETE_ORDER_STATUS_RESET = "DELETE_ORDER_STATUS_RESET";
export const DELETE_ORDER_STATUS_FAIL = "DELETE_ORDER_STATUS_FAIL";

export const ORDER_STATUS_DETAILS_REQUEST = "ORDER_STATUS_DETAILS_REQUEST";
export const ORDER_STATUS_DETAILS_SUCCESS = "ORDER_STATUS_DETAILS_SUCCESS";
export const ORDER_STATUS_DETAILS_FAIL = "ORDER_STATUS_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
